<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account ID' => '',
    'Address' => '',
    'Address Type' => '',
    'Address2' => '',
    'Allow Up Icon' => '',
    'Avatar' => '',
    'Beta' => '',
    'Category' => '',
    'City' => '',
    'Collection Extension' => '',
    'Collection ID' => '',
    'Collection Name' => '',
    'Collection Supported Type' => '',
    'Company' => '',
    'Cookie Hash' => '',
    'Created Date' => '',
    'Cv ID' => '',
    'Defined As' => '',
    'Description' => '',
    'Disable' => '',
    'Disabled Date' => '',
    'Diskspace Cap' => '',
    'Display Order' => '',
    'Email' => '',
    'Facetime ID' => '',
    'Fax Number' => '',
    'First Name' => '',
    'Full Name' => '',
    'ID' => '',
    'Icon Image' => '',
    'Image' => '',
    'Is Admin' => '',
    'Is Deleted' => '',
    'Is Frozen' => '',
    'Is Owner' => '',
    'Is Public' => '',
    'Is Superadmin' => '',
    'Keywords' => '',
    'Kiosk Bookmark Iv ID' => '',
    'Last Loggedin Date' => '',
    'Last Name' => '',
    'Login Name' => '',
    'Member ID' => '',
    'Member Type' => '',
    'Middle Name' => '',
    'Mrp' => '',
    'Name' => '',
    'Packing' => '',
    'Password' => '',
    'Phone Number' => '',
    'Price' => '',
    'Priv Administer' => '',
    'Priv New Forms' => '',
    'Priv New Themes' => '',
    'Public Description' => '',
    'Rc Help Comment' => '',
    'Registered Date' => '',
    'Shared' => '',
    'Sku' => '',
    'State' => '',
    'Status' => '',
    'Stock' => '',
    'T A ID' => '',
    'Type' => '',
    'Updated Date' => '',
    'Upload Folder' => '',
    'Zip' => '',
];
